services:
  prism-xrp:
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - RUST_LOG=info
      - SYMBOLS=xrpusdt
      - SYMBOLS_SPT=xrpusdt
      - SYMBOLS_FUT=xrpusdt
      - TABLE_FUT=features_xrpusdt_future3
      - TABLE_SPT=features_xrpusdt_spot3
      - CHANNEL_CAPACITY=999
      - DATA_DUMP=true
    restart: unless-stopped

  # prism-doge:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   environment:
  #     - RUST_LOG=info
  #     - SYMBOLS=dogeusdt
  #     - TABLE=features_dogeusdt
  #   restart: unless-stopped
