services:
  prism-xrp:
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - RUST_LOG=debug
      # Symbols
      - SYMBOLS_BINANCE_FUT=xrpusdt
      - SYMBOLS_BINANCE_SPT=xrpusdt
      - SYMBOLS_UPBIT_KRW=KRW-XRP
      - SYMBOLS_UPBIT_BTC=BTC-XRP
      - SYMBOLS_UPBIT_USDT=USDT-XRP
      # Database
      - TABLE_FUT=features_xrpusdt_future3
      - TABLE_SPT=features_xrpusdt_spot3
      # Other
      - CHANNEL_CAPACITY=999
      - DATA_DUMP=false
    restart: unless-stopped

  # prism-doge:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   environment:
  #     - RUST_LOG=info
  #     - SYMBOLS=dogeusdt
  #     - TABLE=features_dogeusdt
  #   restart: unless-stopped
